# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='question',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 28, 1, 39, 15, 311305, tzinfo=utc), verbose_name='date created'),
        ),
    ]
