# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0004_auto_20170128_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='date_updated',
            field=models.DateTimeField(null=True, verbose_name='date updated'),
        ),
    ]
